#! /usr/bin/python

import numpy as np
from pycbc import DYN_RANGE_FAC
from pycbc.types import FrequencySeries

f_low = 0
f_high = 4000
df = 0.25

freqs = np.arange(f_low,f_high+df, df)
vals = np.zeros(len(freqs))

for i in range(len(freqs)):
    if i == 0:
        vals[i] = 0.0
    else:
        vals[i] = freqs[i]**(-7./3)

SOLARMASS = 1.989e30
NEWTONS_G = 6.67e-11
C = 299792458
METER_PER_MEGAPARSEC = 3.086E22
RHO_o = 8
PI = 3.141592654
ARM_LENGTH_NM = 4e12

M = (1.219 * SOLARMASS * NEWTONS_G) / C**2;

r_o = M**(5.0/6.0)
r_o *= (5**0.5) * (96.0 * PI**(4.0/3.0) * RHO_o**2)**(-0.5)
r_o *= C**(1.0/6.0)
r_o *= (3*1.84)**(1.0/3.0)
r_o *= 1.0/METER_PER_MEGAPARSEC*ARM_LENGTH_NM

r_o = r_o**2

r_o *= vals

r_o *= DYN_RANGE_FAC**2

spectrum = FrequencySeries(r_o, delta_f=df)

spectrum.save('test_f_7_3.txt')
